name: Master Branch Debugger

on:
    push:
        branches:
            - master

jobs:
    DebugLikeHell:
        name: DebugLikeHell
        runs-on: ubuntu-latest
        steps:
            - name: Prepare
              id: prep
              run: |
                  echo "::notice ref=$GITHUB_REF"
